### ISSUE TITLE
Transforming pointclouds - more channels

### ISSUE THREAD

**Issue by peci1** [ika-rwth-aachen/message_tf_frame_transformer#1]
Hi, I've stumbled upon this package. It looks interesting, but I just wanted to let you know there is a problem when transforming pointclouds - they can have multiple channels, and usually, transforming just the position channel ('x', 'y' and 'z' fields) makes the whole pointcloud inconsistent. What's worse, some pointcloud channels have the meaning of positions, while others denote just vectors/orientation (e.g. normals). With positions, you want to apply both rotation and translation. With vectors, you only want to apply rotation.

We already have a utility library for doing that: https://github.com/ctu-vras/ros-utils/blob/master/cras_cpp_common/include/cras_cpp_common/tf2_sensor_msgs.h, https://github.com/ctu-vras/ros-utils/blob/master/cras_cpp_common/src/tf2_sensor_msgs.cpp .

The thing is, the user can define his own channels not known to the transform node in advance. It is therefore needed to be able to provide some configuration for the pointcloud transforms.

Of course, in the simple case of a XYZI pointcloud, this package works correctly.

**Comment by lreiher** [comment]
Hi, sorry for the delayed response, I have somehow missed this issue.

Obviously you are right about point clouds that have more than the XYZI channels. The thing about this package, however, is that it works generically for all the supported message types. Having dedicated arguments to provide more details about point cloud channels would somehow go against this principle.

Do you have any suggestion on how we could handle this? Otherwise I think it might just be a limitation.

**Comment by peci1** [comment]
No problem, it was just a suggestion and a heads up that there's a potential issue in your use of the library. Your library doesn't need to handle everything.

What I did in some projects was keeping a list of well known channels and whether they are point-like or vector-like. Off the top of my head:

- `{xyz}`, `vp_{xyz}` (viewpoint) are point-like
- `normal_{xyz}` is vector-like
- `rgb`, `r`, `g`, `b`, `t` (timestamp), `time`, `timestamp`, `i` (intensity), `ring`, `ambient`, `reflectivity` are scalars

If you'd like, you could take these lists from ROS parameters (with the well-known lists as defaults). The users could then add their own channels to the corresponding lists if they need.

**Comment by lreiher** [comment]
I do want to keep the implementation completely generic, so don't really want to implement support for PointCloud-only parameter parsing.

Instead, I guess the simplest solution would be to just add a warning message to the README.

**Comment by peci1** [comment]
Do as you like ;)
